#!/bin/bash

INSTALLED=".config/INSTALLED"

echo "请确认您明白您现在进行的操作的后果！"
echo "请确认您明白您现在进行的操作的后果！"
echo "请确认您明白您现在进行的操作的后果！"
echo -n "是否继续(no/yes)"
read anw
if [[ $anw == "yes" ]]
	then 
		echo "开始清理........"
		if [ !  -e $INSTALLED ]
		then 
			echo "缺少配置文件，正在退出....."
			exit 1
		else
			while read line
			do
				echo "rf ${line}"
				rm -rf ${line}
			done < $INSTALLED
        rm $INSTALLED
        fi

else
	echo "正在退出..."
	exit 1
fi

