#!/bin/bash

CONFIG=".config"
NUM="$CONFIG/NUM"
IP="$CONFIG/IP"
USERNAME="$CONFIG/USERNUM"
num=`cat $NUM`
dir=`pwd`
i=1
while read line 
do
	ip[$i]=${line}
	if [ $i != 1 ]
	then 
        echo $i
		zookeeper_c="$zookeeper_c,${line}:2181"
	else
		zookeeper_c="${line}:2181"
	fi
	i=$[i+1]
done < $IP

FOLDER="kafka"
cd $FOLDER
found_kafka=`ls | grep "tgz$"`
if [[ $found_kafka == "" ]]
then
	echo 
	echo "没有找到kafka安装包，请确保在目录kafka下放置了安装包"
else 
	echo "发现安装包$found_kafka"
	tar -zvxf $found_kafka
	for file in *
	do 
		if test -d $file
        then
            z_path="$file"
		fi
	done
	echo "请输入kafka安装路径,默认安装到：/home/$USER/kafka/$z_path"
	echo -n "安装到默认路径?(yes/no):"
	read anw
	if [[ $anw == "no" ]]
	then 
		echo -n "请输入安装路径:"
		read path
	else
		path="/home/$USER/kafka/"
    fi
	#以后需要测试用户输入的path是否存在  
    echo $path >>"$dir/$CONFIG/INSTALLED"
    mkdir $path
    mv "$z_path/" $path 
	
	echo "开始配置"
	cd $path$z_path
	echo "安装集群模式中"
	echo "请输入kafka log路径,默认设置为：/home/$USER/kafka/kafka-log"
	echo -n "安装到默认路径?(yes/no):"
	read l_anw
	if [[ $l_anw == "no" ]]
	then
		echo -n "请输入kafka log路径："
		read l_path
	else 
		l_path=/home/$USER/kafka/kafka-log
	fi
	echo "其他属性暂时设为默认值"
	mkdir $l_path
	sed -i '/^'broker.id='/d' config/server.properties
	sed -i '/# The id of the broker. This must be set to a unique integer for each broke/a\broker.id=1' config/server.properties
	
    sed -i '/#port=9092/a\port=9092' config/server.properties

	ip_host=`hostname -i`
	sed -i '/^'host.name='/d' config/server.properties
	sed -i '/# Hostname the broker will bind to/a\host.name='$ip_host'' config/server.properties
	
	sed -i '/^'log.dirs='/d' config/server.properties
	sed -i '/# A comma seperated list /a\log.dirs='$l_path'' config/server.properties
    
    sed -i '/socket.request.max /a\delete.topic.enable=true' config/server.properties

    sed -i '/# from the end of the log/a\log.roll.hours=2' config/server.properties

    sed -i '/^'log.retention.hours='/d' config/server.properties
    sed -i '/# The minimum age of a log file/a\log.retention.hours=24' config/server.properties

    sed -i '/#log.retention.bytes/a\log.retention.bytes=1073741824' config/server.properties

    sed -i '/^'log.segment.bytes='/d' config/server.properties
    echo "log.segment.bytes=1048576" >>config/server.properties
    echo "log.cleanup.policy=delete" >> config/server.properties
    sed -i '/^'log.retention.check.interval.ms='/d' config/server.properties

    echo "log.retention.check.interval.ms=60000" >> config/server.properties
    


    echo $zookeeper_c
	sed -i '/^'zookeeper.connect='/d' config/server.properties
	sed -i '/# root directory for all kafka znodes./a\zookeeper.connect='$zookeeper_c'' config/server.properties

	
    echo "本机配置完成，分发到集群中其他机器"
	j=2
    
    echo $dir/$USERNAME
    cat $dir/$USERNAME | while read line
    do
        scp -r $path "${line}@""${ip[$j]}"":$path"
		
		cp config/server.properties config/server.properties.tmp
		sed -i '/^'broker.id='/d' config/server.properties.tmp
		sed -i '/# The id of the broker. This must be set to a unique integer for each broke/a\broker.id='$j'' config/server.properties.tmp
		
		sed -i '/^'host.name='/d' config/server.properties.tmp
		sed -i '/# Hostname the broker will bind to/a\host.name='${ip[$j]}'' config/server.properties.tmp
		
		scp config/server.properties.tmp "${line}@""${ip[$j]}"":$path$z_path/config/server.properties"
		
		
        j=$[j+1]
    done

fi
