#!/bin/bash

# usage
if [ $# -ne 4 ]
then
  echo "usage: ./configKafka mode kafka_num cur_path install_path"
  exit 1
fi

# init
__CUR_PATH__=$3
__INSTALL_PATH__=$4

function GetKey(){
  section=$(echo $1 | cut -d '.' -f 1)
  key=$(echo $1 | cut -d '.' -f 2)
  sed -n "/\[$section\]/,/\[.*\]/{
    /^\[.*\]/d
    /^[ \t]*$/d
    /^$/d
    /^#.*$/d
    s/^[ \t]*$key[ \t]*=[ \t]*\(.*\)[ \t]*/\1/p
  }" ${__CUR_PATH__}/config
}

# start configure
echo "配置 kafka"
tar -xzf ${__CUR_PATH__}/kafka/kafka_*.tgz -C ${__INSTALL_PATH__}
KAFKA_HOME=$(cd ${__INSTALL_PATH__}/kafka_*; pwd)
mkdir ${__INSTALL_PATH__}/kafka-logs $KAFKA_HOME/logs
cp -f ${__CUR_PATH__}/conf$1/server.properties $KAFKA_HOME/config/server.properties
if [ $1 -eq 0 ]
then
  echo "log.dirs=${__INSTALL_PATH__}/kafka-logs" >> $KAFKA_HOME/config/server.properties
  BROKER_LIST=localhost:9092
else
  echo "broker.id=$2" >> $KAFKA_HOME/config/server.properties
  echo "host.name=$(GetKey "kafka.HOST$2")" >> $KAFKA_HOME/config/server.properties
  echo "log.dirs=${__INSTALL_PATH__}/kafka-logs" >> $KAFKA_HOME/config/server.properties
  server_num=$(GetKey zookeeper.SERVER_NUM)
  for((i=1;i<=server_num;i++)); do ZK_HOSTS_K+="$(GetKey "zookeeper.IP$i"):2181,"; done
  ZK_HOSTS_K=${ZK_HOSTS_K%,*}
  echo "zookeeper.connect=$ZK_HOSTS_K" >> $KAFKA_HOME/config/server.properties
  broker_num=$(GetKey kafka.BROKER_NUM)
  for((i=1;i<=broker_num;i++)); do BROKER_LIST+="$(GetKey "kafka.HOST$i"):9092,"; done
  BROKER_LIST=${BROKER_LIST%,*}
fi
echo "export KAFKA_HOME=$KAFKA_HOME" >> ~/.bashrc
echo "export BROKER_LIST=$BROKER_LIST" >> ~/.bashrc
