#!/bin/bash

# usage
if [ $# -ne 4 ]
then
  echo "usage: ./configStorm mode storm_num cur_path install_path"
  exit 1
fi

# init
__CUR_PATH__=$3
__INSTALL_PATH__=$4

function GetKey(){
  section=$(echo $1 | cut -d '.' -f 1)
  key=$(echo $1 | cut -d '.' -f 2)
  sed -n "/\[$section\]/,/\[.*\]/{
    /^\[.*\]/d
    /^[ \t]*$/d
    /^$/d
    /^#.*$/d
    s/^[ \t]*$key[ \t]*=[ \t]*\(.*\)[ \t]*/\1/p
  }" ${__CUR_PATH__}/config
}

# start configure
echo "配置 storm"
tar -xzf ${__CUR_PATH__}/storm/apache-storm-*.tar.gz -C ${__INSTALL_PATH__}
STORM_HOME=$(cd ${__INSTALL_PATH__}/apache-storm-*; pwd)
mkdir -p ${__INSTALL_PATH__}/storm-workdir $STORM_HOME/logs
if [ $1 -eq 0 ]
then
  cp -f ${__CUR_PATH__}/conf$1/storm.yaml $STORM_HOME/conf/storm.yaml
  echo "storm.local.dir: \"${__INSTALL_PATH__}/storm-workdir\"" >> $STORM_HOME/conf/storm.yaml
else
  echo "storm.zookeeper.servers:" >> $STORM_HOME/conf/storm.yaml
  server_num=$(GetKey zookeeper.SERVER_NUM)
  for((i=1;i<=server_num;i++)); do echo "    - \"$(GetKey "zookeeper.IP$i")\"" >> $STORM_HOME/conf/storm.yaml; done
  nimbus_num=$(GetKey storm.NIMBUS_NUM)
  for((i=1;i<=nimbus_num;i++)); do nimbus_seeds+="\"$(GetKey "storm.HOST$i")\","; done
  nimbus_seeds=${nimbus_seeds%,*}
  echo "nimbus.seeds: [$nimbus_seeds]" >> $STORM_HOME/conf/storm.yaml
  echo "storm.local.dir: \"${__INSTALL_PATH__}/storm-workdir\"" >> $STORM_HOME/conf/storm.yaml
  echo "supervisor.slots.ports:" >> $STORM_HOME/conf/storm.yaml
  echo "    - 6700" >> $STORM_HOME/conf/storm.yaml
  echo "    - 6701" >> $STORM_HOME/conf/storm.yaml
  echo "    - 6702" >> $STORM_HOME/conf/storm.yaml
  echo "    - 6703" >> $STORM_HOME/conf/storm.yaml
fi
echo "export STORM_HOME=$STORM_HOME" >> ~/.bashrc
