#!/bin/bash

CONFIG=".config"
NUM="$CONFIG/NUM"
IP="$CONFIG/IP"
USERNAME="$CONFIG/USERNUM"
num=`cat $NUM`
dir=`pwd`
declare -a ip
FOLDER="zookeeper"
cd $FOLDER
found_zookeeper=`ls | grep "tar.gz$"`
if [[ $found_zookeeper == "" ]]
then
	echo 
	echo "没有找到zookeeper安装包，请确保在目录zookeeper下放置了安装包"
else 
	echo "发现安装包$found_zookeeper"
	tar -zvxf $found_zookeeper
	for file in *
	do 
		if test -d $file
        then
            z_path="$file"
		fi
	done
	echo "请输入zookeeper安装路径,默认安装到：/home/$USER/zookeeper/$z_path"
	echo -n "安装到默认路径?(yes/no):"
	read anw
	if [[ $anw == "no" ]]
	then 
		echo -n "请输入安装路径:"
		read path
	else
		path="/home/$USER/zookeeper/"
    fi

	#以后需要测试用户输入的path是否存在  
	echo $path > "$dir/$CONFIG/INSTALLED"
    mkdir $path
    mv "$z_path/" "$path/"
	
	echo "开始配置"
	cd $path$z_path
	cp conf/zoo_sample.cfg conf/zoo.cfg
	echo "安装集群模式中"
	echo "请输入zookeeper data路径,默认设置为：/home/$USER/zookeeper/zookeeper-data"
	echo -n "安装到默认路径?(yes/no):"
	read d_anw
	if [[ $d_anw == "no" ]]
	then
		echo -n "请输入zookeeper data路径："
		read d_path
	else 
		d_path=/home/$USER/zookeeper/zookeeper-data
	fi
	echo "请输入zookeeper log路径,默认设置为：/home/$USER/zookeeper/zookeeper-log"
	echo -n "安装到默认路径?(yes/no):"
	read l_anw
	if [[ $l_anw == "no" ]]
	then
		echo -n "请输入zookeeper log路径："
		read l_path
	else 
		l_path=/home/$USER/zookeeper/zookeeper-log
	fi
	echo "其他属性暂时设为默认值"
	mkdir $d_path
	mkdir $l_path
	echo "">conf/zoo.cfg
	echo "#created by auto" > conf/zoo.cfg
	echo "tickTime=2000" >> conf/zoo.cfg
	echo "initLimit=10" >> conf/zoo.cfg
	echo "syncLimit=5" >> conf/zoo.cfg
	echo "dataDir=$d_path" >> conf/zoo.cfg
	echo "dataLogDir=$l_path" >>conf/zoo.cfg
	echo "clientPort=2181" >> conf/zoo.cfg
    echo "autopurge.purgeInterval=1" >>conf/zoo.cfg
    echo "autopurge.snapRetainCount=3" >>conf/zoo.cfg
    echo "1" > $d_path/myid

    i=1
    cd -
    cd ..
	#cat $IP | while read line 
    while read line 
    do
        ip[$i]=${line}
        echo $i
        echo "${ip[$i]}"
        echo "server.$i=${line}:2888:3888">> $path$z_path/conf/zoo.cfg
        i=$[i+1]
    done < $IP
    echo "本机配置完成，分发到集群中其他机器"
	j=2
    cat $USERNAME | while read line
    do
        scp -r $path "${line}@${ip[$j]}:$path"
		echo "$j"> myid$j
		scp myid$j "${line}@${ip[$j]}:$d_path/myid"
		rm myid$j
        j=$[j+1]
    done

fi
